### ISSUE TITLE
处理出错的场景

### ISSUE THREAD

**Issue by sorrycc** [umijs/plugin-initial-state#2]
比如：

```js
export async function getInitialState() {
  throw new Error('x');
}
```

现在直接运行时抛错了。

**Comment by ttys026** [comment]
如果用 try catch 包裹之后，throw error 的情况下，return 值可能还是一个 undefined，这样的话，消费时进行解构还是可能抛错。

预期的出错处理是什么样比较合适呢 @sorrycc

**Comment by sorrycc** [comment]
出错时 `return { error }`，使用时 `const { initialState, error } = useModel('@@initialState');`。这样？
